# Build React App
FROM node:22-slim AS builder
WORKDIR /app
COPY frontend/package.json frontend/package-lock.json ./frontend/
RUN cd frontend && npm install
COPY frontend ./frontend
RUN cd frontend && npm run build

# Build Express Server
FROM node:22-slim AS server
WORKDIR /app
COPY express/package.json express/package-lock.json ./express/
RUN cd express && npm install && rm -rf /root/.npm
COPY express ./express

# Copy built frontend to backend
COPY --from=builder /app/frontend/dist ./frontend/dist

# Set environment variables
ENV NODE_ENV=production
WORKDIR /app/express
CMD ["node", "server.js"]
EXPOSE 5000

